name: 'Repo Performance'
author: 'ToyB0x'
description: 'Analyze repository metrics'
branding:
  color: 'blue'
  icon: 'activity'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: npm install -g tsx
      shell: bash

    - name: Run performance analysis
      run: npx @ts-bench/db migrate
      shell: bash
      env:
        DB_FILE_NAME: "ts-bench.sqlite"

    - name: Run performance analysis
      run: npx @ts-bench/cli@latest analyze > report.md
      shell: bash
      env:
        DB_FILE_NAME: "ts-bench.sqlite"
