CREATE TABLE `result` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`package` text NOT NULL,
	`is_success` integer NOT NULL,
	`is_cached` integer NOT NULL,
	`scan_id` integer NOT NULL,
	`trace_num_type` integer,
	`trace_num_trace` integer,
	`trace_file_size_type` integer,
	`trace_file_size_trace` integer,
	`num_hot_spot` integer,
	`duration_ms_hot_spot` numeric,
	`analyze_file_size` integer,
	`files` integer,
	`lines_of_library` integer,
	`lines_of_definitions` integer,
	`lines_of_typescript` integer,
	`lines_of_javascript` integer,
	`lines_of_json` integer,
	`lines_of_other` integer,
	`identifiers` integer,
	`symbols` integer,
	`types` integer,
	`instantiations` integer,
	`memory_used` integer,
	`assignability_cache_size` integer,
	`identity_cache_size` integer,
	`subtype_cache_size` integer,
	`strict_subtype_cache_size` integer,
	`tracing_time` numeric,
	`io_read_time` numeric,
	`parse_time` numeric,
	`resolve_module_time` numeric,
	`resolve_type_reference_time` numeric,
	`resolve_library_time` numeric,
	`program_time` numeric,
	`bind_time` numeric,
	`check_time` numeric,
	`print_time` numeric,
	`emit_time` numeric,
	`dump_types_time` numeric,
	`total_time` numeric,
	`error` text,
	FOREIGN KEY (`scan_id`) REFERENCES `scan`(`id`) ON UPDATE cascade ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_result_scanId_package` ON `result` (`scan_id`,`package`);--> statement-breakpoint
CREATE TABLE `scan` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`version` text NOT NULL,
	`owner` text NOT NULL,
	`repository` text NOT NULL,
	`changed` integer,
	`files` integer,
	`insertions` integer,
	`deletions` integer,
	`commit_hash` text NOT NULL,
	`commit_message` text NOT NULL,
	`commit_data` integer NOT NULL,
	`scanned_at` integer DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	`cpus` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `uq_scan_repository_commit_hash` ON `scan` (`repository`,`commit_hash`);